
account_exec:
	java -jar target/dubbo-demo-misc-seata-1.0-SNAPSHOT.jar account

business_exec:
	java -jar target/dubbo-demo-misc-seata-1.0-SNAPSHOT.jar business

order_exec:
	java -jar target/dubbo-demo-misc-seata-1.0-SNAPSHOT.jar order

storage_exec:
	java -jar target/dubbo-demo-misc-seata-1.0-SNAPSHOT.jar storage
